(cons 1 (cons 2 (cons 3 (cons 4 nil))))
(list 1 2 3 4)
(car '(a b c))
(cdr '(a b c))
(car '(cdr '(cdr '(a b c d e))))
(caddr '(a b c d e))
(eq 'x 'x)
(eq '(a b) '(a b))
(eql 3 3)
(eql 2.0 2)
(equal 'x 'x)
(equal '(a b c) '(a b c))
(null '())
(atom 'x)
(atom nil)
(car '(cdr '(cons 'a '(b c))))
(cons (caddr '(a b c d)) (cons (car '(a b c d)) (cons (cadr '(a b c d)) (cons ( cadddr '(a b c d)) nil) )))
(list (caddr '(a b c d)) (car '(a b c d)) (cadr '(a b c d)) (cadddr '(a b c d)))
(list (nth 2 '(a b c d)) (first '(a b c d)) (second '(a b c d)) (car (last '(a b c d))))
(caddr '(a b c d))
(cadddr '(1 2 3 4 5 6 7 8 9 0 11 12 13 14 15 16 17 18))
